//! Splice-time patcher for the `splicer:builtin-config` provider
//! template.
//!
//! The provider template is built like any other builtin
//! (`builtins/config-provider/`). It exports
//! `splicer:builtin-config/get` and reads its key/value table from a
//! fixed-capacity `static` buffer in its core module. The Rust crate
//! pads that buffer with a known magic sentinel so a byte-scan can
//! locate it from the outside.
//!
//! `build_provider` loads the template bytes (override → cache → OCI),
//! serializes the caller's KV map into the table's wire format, and
//! overwrites the bytes after the magic. The data segment's total
//! length is preserved; the in-component parser uses the length field
//! to bound iteration so trailing padding stays inert.
//!
//! Why byte-scan instead of a structural rewrite (wasm-encoder)?
//! Same reason the original design picked patching over codegen:
//! per-splice work is one in-place edit, and the template is built
//! once at builtin-publish time.

use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::path::Path;

use crate::builtins;
use crate::parse::config::Injection;

// `BUILTIN_CONFIG_PACKAGE` / `BUILTIN_CONFIG_VERSION` /
// `BUILTIN_CONFIG_GET` / `BUILTIN_CONFIG_GET_VERSIONED` /
// `BUILTIN_CONFIG_INTERFACES` — generated by build.rs from
// `wit/builtin-config/world.wit`. Bumping the WIT package version
// is the only edit needed to propagate the new version everywhere.
include!(concat!(env!("OUT_DIR"), "/builtin_config_constants.rs"));

// Wire-format constants AND codec (serialize_table / deserialize_table
// / read_u32_le) shared with the provider template
// (`builtins/config-provider/src/wire_format.rs`), which loads the
// same file via `mod wire_format;`. Do not duplicate the format here.
#[path = "../builtins/config-provider/src/wire_format.rs"]
mod wire_format;

use wire_format::{serialize_table, CAPACITY, LEN_PREFIX_BYTES, MAGIC_BYTES, MAGIC_LEN};

/// Name of the provider template builtin. Mirrors the crate dir under
/// `builtins/` (no canonical source above the directory name itself).
/// Referenced from `builtins::INTERNAL_BUILTINS` so users can't
/// inject it directly from YAML.
pub(crate) const PROVIDER_BUILTIN_NAME: &str = "config-provider";

/// Bytes the serialized table can use after the magic + length header.
const MAX_PAYLOAD: usize = CAPACITY - MAGIC_LEN - LEN_PREFIX_BYTES;

/// If `injection.path` points at a wasm component that imports
/// `splicer:builtin-config`, build a patched provider with
/// `injection.builtin_config` baked in, write it under
/// `<splits_dir>/builtins/<wac_var>-config.wasm`, and stamp the
/// resulting path onto `injection.config_provider_path`.
///
/// Idempotent: if `injection.config_provider_path` is already set,
/// returns without re-doing the work. Returns without writing when
/// the injection isn't a builtin, has no materialized path yet, or
/// doesn't import the substrate.
pub fn ensure_provider_for(injection: &mut Injection, splits_dir: &Path) -> Result<()> {
    if injection.config_provider_path.is_some() {
        return Ok(());
    }
    let Some(builtin_path) = injection.path.as_deref() else {
        return Ok(());
    };
    let bytes = std::fs::read(builtin_path)
        .with_context(|| format!("Failed to read materialized builtin '{}'", builtin_path))?;
    if !imports_substrate(&bytes) {
        return Ok(());
    }
    let provider_bytes = build_provider(&injection.builtin_config).with_context(|| {
        format!(
            "Failed to build config provider for injection '{}'",
            injection.name
        )
    })?;

    // Write alongside the materialized builtin under `<splits>/builtins/`.
    // The dir is created by `materialize_into` before this runs, but the
    // create-all keeps the function self-contained in case a caller wires
    // it independently of the standard pipeline.
    let dir = splits_dir.join("builtins");
    std::fs::create_dir_all(&dir)
        .with_context(|| format!("Failed to create builtins dir: {}", dir.display()))?;
    let out = dir.join(format!("{}-config.wasm", injection.name));
    std::fs::write(&out, &provider_bytes)
        .with_context(|| format!("Failed to write config provider: {}", out.display()))?;

    let out_str = out
        .to_str()
        .ok_or_else(|| {
            anyhow::anyhow!(
                "config provider path contains non-UTF-8 bytes: {}",
                out.display()
            )
        })?
        .to_string();
    injection.config_provider_path = Some(out_str);
    Ok(())
}

/// True iff the component bytes declare an import of any interface in
/// the `splicer:builtin-config` package. Best-effort: returns `false`
/// on decode errors, mirroring `resource_bearing_imports` in
/// `src/wac.rs`. The downstream consequence of a false negative is
/// the same as for a builtin that genuinely doesn't import the
/// substrate — no provider is wired — so a hard failure isn't useful.
fn imports_substrate(bytes: &[u8]) -> bool {
    let Ok(decoded) = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        wit_component::decode(bytes)
    })) else {
        return false;
    };
    let Ok(wit_component::DecodedWasm::Component(resolve, world_id)) = decoded else {
        return false;
    };
    let world = &resolve.worlds[world_id];
    for (_key, item) in &world.imports {
        let wit_parser::WorldItem::Interface { id, .. } = item else {
            continue;
        };
        let Some(name) = resolve.id_of(*id) else {
            continue;
        };
        // `id_of` returns the qualified name (e.g.
        // `splicer:builtin-config/get@0.1.0`); the package prefix +
        // `/` test isolates this package without coupling the check
        // to whatever interface(s) it ends up exposing later.
        if name.starts_with(&format!("{BUILTIN_CONFIG_PACKAGE}/")) {
            return true;
        }
    }
    false
}

/// Build a patched provider component with `values` baked in.
///
/// Returns the wasm bytes ready to write to disk and reference from
/// the WAC composition. The fully-qualified WIT export the bytes
/// satisfy is `splicer:builtin-config/get@0.1.0`.
///
/// Fails if:
/// - The provider template can't be resolved (no override + no cache +
///   no network).
/// - The magic sentinel doesn't appear exactly once in the template.
///   This signals the template was rebuilt against an out-of-date
///   `MAGIC`, or that the build elided the static.
/// - The serialized table exceeds the reserved capacity.
pub fn build_provider(values: &BTreeMap<String, String>) -> Result<Vec<u8>> {
    let mut bytes = builtins::load_resolved_bytes(PROVIDER_BUILTIN_NAME)
        .context("Failed to load config-provider template bytes")?;
    patch_in_place(&mut bytes, values)?;
    Ok(bytes)
}

/// Locate `MAGIC_BYTES` in `bytes` and overwrite the bytes that
/// follow with the serialized KV table.
fn patch_in_place(bytes: &mut [u8], values: &BTreeMap<String, String>) -> Result<()> {
    let payload = serialize_table(values);
    if payload.len() > MAX_PAYLOAD {
        anyhow::bail!(
            "config-provider payload of {} bytes exceeds reserved capacity of {} bytes \
             (template `CAPACITY` minus magic + length header). Either trim the config or \
             rebuild the provider with a larger `CAPACITY`.",
            payload.len(),
            MAX_PAYLOAD,
        );
    }
    let offset = find_unique_magic(bytes)?;
    // [magic][u32 LE payload_len][payload bytes][unchanged padding]
    let len_off = offset + MAGIC_LEN;
    let payload_off = len_off + LEN_PREFIX_BYTES;
    let payload_end = payload_off + payload.len();
    bytes[len_off..len_off + LEN_PREFIX_BYTES]
        .copy_from_slice(&(payload.len() as u32).to_le_bytes());
    bytes[payload_off..payload_end].copy_from_slice(&payload);
    Ok(())
}

/// Return the byte offset of the single occurrence of `MAGIC_BYTES`
/// in `bytes`. Fails if the magic isn't found or appears more than
/// once (either is a template/build problem the user can't fix by
/// retrying — surface clearly).
fn find_unique_magic(bytes: &[u8]) -> Result<usize> {
    let mut found: Option<usize> = None;
    let mut i = 0;
    while i + MAGIC_LEN <= bytes.len() {
        if bytes[i..i + MAGIC_LEN] == MAGIC_BYTES {
            if found.is_some() {
                anyhow::bail!(
                    "config-provider template has multiple `MAGIC_BYTES` matches. The byte-scan \
                     patcher assumes exactly one. Check the template build."
                );
            }
            found = Some(i);
            // Magic is long enough that it can't overlap with itself;
            // skip past to keep the scan O(n).
            i += MAGIC_LEN;
        } else {
            i += 1;
        }
    }
    found.ok_or_else(|| {
        anyhow::anyhow!(
            "config-provider template is missing the magic sentinel. The template was \
             either built against an out-of-date `MAGIC_BYTES`, or the compiler elided \
             the KV buffer. Rebuild builtins/config-provider with the in-tree sources."
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config_provider::wire_format::deserialize_table;
    use crate::parse::config::Injection;

    fn make_blob(payload: &[u8]) -> Vec<u8> {
        // Mimics the template's static layout: random prefix, magic,
        // length header, padding to CAPACITY, random suffix. The
        // prefix + suffix make sure the byte-scan ignores everything
        // outside the magic-anchored window.
        let prefix = b"PREFIX_BYTES_BEFORE_MAGIC".to_vec();
        let suffix = b"SUFFIX_BYTES_AFTER_TEMPLATE".to_vec();
        let mut buf = Vec::with_capacity(prefix.len() + CAPACITY + suffix.len());
        buf.extend_from_slice(&prefix);
        buf.extend_from_slice(&MAGIC_BYTES);
        buf.extend_from_slice(&(payload.len() as u32).to_le_bytes());
        buf.extend_from_slice(payload);
        // Pad to CAPACITY total (relative to MAGIC start).
        let written = MAGIC_LEN + LEN_PREFIX_BYTES + payload.len();
        buf.extend(std::iter::repeat_n(0xAA, CAPACITY - written));
        buf.extend_from_slice(&suffix);
        buf
    }

    /// Parse the patched blob back into a HashMap, exercising the
    /// same `wire_format::deserialize_table` the provider runtime
    /// uses — so wire-format drift would surface as a round-trip
    /// failure here, not just in the live builtin.
    fn parse_back(bytes: &[u8]) -> std::collections::HashMap<String, String> {
        let off = find_unique_magic(bytes).expect("magic present");
        let body = &bytes[off + MAGIC_LEN..];
        let payload_len = u32::from_le_bytes(body[..LEN_PREFIX_BYTES].try_into().unwrap()) as usize;
        let payload = &body[LEN_PREFIX_BYTES..LEN_PREFIX_BYTES + payload_len];
        deserialize_table(payload)
    }

    #[test]
    fn round_trip_empty() {
        let mut blob = make_blob(&[]);
        patch_in_place(&mut blob, &BTreeMap::new()).expect("patch");
        let parsed = parse_back(&blob);
        assert!(parsed.is_empty());
    }

    #[test]
    fn round_trip_multi_key() {
        let mut blob = make_blob(&[]);
        let mut values = BTreeMap::new();
        values.insert("buffer".to_string(), "100".to_string());
        values.insert("flush_after_seconds".to_string(), "10.0".to_string());
        values.insert("note".to_string(), "value with spaces and 🎉".to_string());
        patch_in_place(&mut blob, &values).expect("patch");
        let parsed = parse_back(&blob);
        assert_eq!(parsed.len(), values.len());
        for (k, v) in &values {
            assert_eq!(parsed.get(k), Some(v));
        }
    }

    #[test]
    fn missing_key_after_patch_yields_nothing() {
        let mut blob = make_blob(&[]);
        let mut values = BTreeMap::new();
        values.insert("buffer".to_string(), "100".to_string());
        patch_in_place(&mut blob, &values).expect("patch");
        let parsed = parse_back(&blob);
        assert!(!parsed.contains_key("not-set"));
    }

    #[test]
    fn patch_preserves_outside_window() {
        let mut blob = make_blob(&[]);
        let original = blob.clone();
        let mut values = BTreeMap::new();
        values.insert("k".to_string(), "v".to_string());
        patch_in_place(&mut blob, &values).expect("patch");

        // Bytes before MAGIC and after MAGIC + CAPACITY must be unchanged.
        let magic_off = find_unique_magic(&blob).expect("magic");
        let template_end = magic_off + CAPACITY;
        assert_eq!(&blob[..magic_off], &original[..magic_off]);
        assert_eq!(&blob[template_end..], &original[template_end..]);
    }

    #[test]
    fn overflow_rejects_cleanly() {
        let mut blob = make_blob(&[]);
        let mut values = BTreeMap::new();
        // One oversize value pushes past MAX_PAYLOAD.
        values.insert("k".to_string(), "a".repeat(MAX_PAYLOAD));
        let err = patch_in_place(&mut blob, &values).unwrap_err();
        let msg = format!("{err:#}");
        assert!(msg.contains("exceeds reserved capacity"), "{msg}");
    }

    #[test]
    fn missing_magic_surfaces_clear_error() {
        // A template without the sentinel must not silently succeed.
        let bytes = vec![0u8; 1024];
        let err = find_unique_magic(&bytes).unwrap_err();
        let msg = format!("{err:#}");
        assert!(msg.contains("missing the magic sentinel"), "{msg}");
    }

    #[test]
    fn duplicate_magic_surfaces_clear_error() {
        // Belt-and-suspenders: two copies of MAGIC_BYTES means the byte-scan
        // can't decide which one to patch. The template should never
        // produce this, but if it ever did we want to fail loudly.
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&MAGIC_BYTES);
        bytes.extend_from_slice(&[0u8; 64]);
        bytes.extend_from_slice(&MAGIC_BYTES);
        let err = find_unique_magic(&bytes).unwrap_err();
        let msg = format!("{err:#}");
        assert!(msg.contains("multiple `MAGIC_BYTES` matches"), "{msg}");
    }

    /// Regression guard: load the actual built provider template and
    /// confirm `MAGIC_BYTES` appears exactly once. Earlier iterations of
    /// the template had a separate `const MAGIC` referenced at runtime,
    /// which rustc/lld lowered to a second addressable copy in the data
    /// section — silently breaking the patcher. This test exercises
    /// `build_provider` against the resolved template (override → cache
    /// → OCI pull) and fails if the byte-scan finds more than one match.
    ///
    /// Gated as `#[ignore]` because it needs either `SPLICER_BUILTINS_DIR`
    /// pointed at an `assets/builtins/` dir from `make build-builtins`,
    /// or a populated cache, or network access for the OCI fallback.
    /// Run with `cargo test -- --ignored` or set
    /// `SPLICER_BUILTINS_DIR=assets/builtins` and invoke this test by
    /// name to enable it.
    #[test]
    #[ignore = "needs built/cached/registry-resolvable config-provider template"]
    fn built_provider_has_unique_magic() {
        // build_provider's first step is load_resolved_bytes + find_unique_magic;
        // a duplicate match would surface as the "multiple `MAGIC_BYTES`
        // matches" error from the patcher.
        build_provider(&BTreeMap::new())
            .expect("template must resolve and have exactly one MAGIC_BYTES match");
    }

    /// Smoke test: confirm `hello-tier1` (a real shipped builtin)
    /// actually trips `imports_substrate` and that `ensure_provider_for`
    /// produces a patched provider for it. Catches regressions where a
    /// builtin's WIT world stops importing `splicer:builtin-config` or
    /// the byte-scan stops detecting it.
    ///
    /// Same `#[ignore]` rationale as `built_provider_has_unique_magic`:
    /// needs the assets dir or a populated cache.
    #[test]
    #[ignore = "needs built/cached/registry-resolvable hello-tier1 + config-provider"]
    fn hello_tier1_smoke() {
        let hello_bytes =
            crate::builtins::load_resolved_bytes("hello-tier1").expect("hello-tier1 must resolve");
        assert!(
            imports_substrate(&hello_bytes),
            "hello-tier1 must import splicer:builtin-config",
        );

        // Drive the same end-to-end path the splice pipeline takes:
        // ensure_provider_for reads inj.path off disk and writes the
        // patched provider next to it.
        let splits = tempfile::tempdir().unwrap();
        let builtin_dir = splits.path().join("builtins");
        std::fs::create_dir_all(&builtin_dir).unwrap();
        let hello_path = builtin_dir.join("hello-tier1.wasm");
        std::fs::write(&hello_path, &hello_bytes).unwrap();

        let mut inj = Injection::from_path("hello-tier1", hello_path.to_str().unwrap());
        inj.builtin_config
            .insert("greeting".to_string(), "wired-up-end-to-end".to_string());

        ensure_provider_for(&mut inj, splits.path()).expect("ensure_provider_for");
        let provider = inj
            .config_provider_path
            .as_deref()
            .expect("provider path stamped");
        let patched = std::fs::read(provider).expect("provider file written");
        let parsed = parse_back(&patched);
        assert_eq!(
            parsed.get("greeting").map(String::as_str),
            Some("wired-up-end-to-end")
        );
    }

    // ── imports_substrate / ensure_provider_for ─────────────────────

    /// Tiny WAT fixture: a component importing `splicer:builtin-config/get`.
    /// `wit_component::decode` needs the component to declare a world,
    /// but for an external-facing import-only shape with no exports the
    /// decoder still produces a usable Resolve/World pair.
    const CONSUMER_WAT: &str = r#"(component
        (import "splicer:builtin-config/get@0.1.0" (instance
            (export "get" (func (param "key" string) (result (option string))))
        ))
    )"#;

    /// Negative fixture: imports something unrelated, exports nothing.
    const NON_CONSUMER_WAT: &str = r#"(component
        (import "wasi:http/handler@0.3.0" (instance
            (export "handle" (func (param "req" u32) (result u32)))
        ))
    )"#;

    #[test]
    fn imports_substrate_detects_consumer() {
        let bytes = wat::parse_str(CONSUMER_WAT).expect("wat");
        assert!(imports_substrate(&bytes));
    }

    #[test]
    fn imports_substrate_rejects_non_consumer() {
        let bytes = wat::parse_str(NON_CONSUMER_WAT).expect("wat");
        assert!(!imports_substrate(&bytes));
    }

    #[test]
    fn imports_substrate_tolerates_garbage() {
        // Decode failure → false (best-effort, mirrors
        // resource_bearing_imports). A garbage byte string must not
        // panic out of the catch_unwind guard.
        assert!(!imports_substrate(b"not a wasm component"));
    }

    /// End-to-end: with a CONSUMER_WAT-style builtin at `inj.path` and
    /// `with_fake_builtins` priming a real config-provider template,
    /// `ensure_provider_for` should stamp the path and write a patched
    /// component whose magic-anchored body decodes back to the input
    /// values.
    #[test]
    fn ensure_provider_for_writes_patched_component() {
        // Build a real-looking template blob: prefix bytes + MAGIC_BYTES
        // + [u32 len=0] + padding. The patcher only cares about the
        // magic-anchored window, so the surrounding bytes are
        // arbitrary.
        let mut template = Vec::new();
        template.extend_from_slice(b"\0asm\x01\x00\x00\x00fake-prefix-");
        template.extend_from_slice(&MAGIC_BYTES);
        template.extend_from_slice(&0u32.to_le_bytes());
        template.extend(std::iter::repeat_n(
            0xAA,
            CAPACITY - MAGIC_LEN - LEN_PREFIX_BYTES,
        ));
        template.extend_from_slice(b"-fake-suffix");

        // The builtin is the WAT consumer; the provider template is the
        // synthetic blob above. Both live in SPLICER_BUILTINS_DIR.
        let consumer_bytes = wat::parse_str(CONSUMER_WAT).expect("wat");
        let splits = tempfile::tempdir().unwrap();
        let builtin_dir = splits.path().join("builtins");
        std::fs::create_dir_all(&builtin_dir).unwrap();
        let builtin_path = builtin_dir.join("fake-consumer.wasm");
        std::fs::write(&builtin_path, &consumer_bytes).unwrap();

        // Write the synthetic config-provider template to a temp
        // override dir. `with_fake_builtins` lets us prime overrides
        // for arbitrary names, but only with the magic-bytes fixture
        // — for this test we override directly via the env var so we
        // can plant our richer template.
        let override_dir = tempfile::tempdir().unwrap();
        std::fs::write(override_dir.path().join("config-provider.wasm"), &template).unwrap();
        let _guard = EnvGuard::set("SPLICER_BUILTINS_DIR", override_dir.path());

        let mut inj = Injection::from_path("metrics", builtin_path.to_str().unwrap());
        inj.builtin_config.insert("buffer".into(), "100".into());
        inj.builtin_config
            .insert("flush_after_seconds".into(), "10.0".into());

        ensure_provider_for(&mut inj, splits.path()).expect("ensure");

        let path = inj
            .config_provider_path
            .as_deref()
            .expect("provider path stamped");
        let patched = std::fs::read(path).expect("provider written");
        let parsed = parse_back(&patched);
        assert_eq!(parsed.get("buffer").map(String::as_str), Some("100"));
        assert_eq!(
            parsed.get("flush_after_seconds").map(String::as_str),
            Some("10.0")
        );
    }

    /// YAML with no `config:` block still has to produce a working
    /// provider when the builtin imports the substrate: empty
    /// `inj.builtin_config` → provider with `payload_len = 4`
    /// (`count = 0`) → runtime returns `None` for every key →
    /// consumer falls back to its hardcoded defaults. This exercises
    /// the path users hit when they just write `builtin: <name>`
    /// without any `config:` entries.
    #[test]
    fn ensure_provider_for_emits_provider_with_empty_config() {
        // Synthetic template: prefix bytes + MAGIC_BYTES + zero
        // payload_len + 0xAA padding. The patcher only cares about
        // the magic-anchored window.
        let mut template = Vec::new();
        template.extend_from_slice(b"\0asm\x01\x00\x00\x00fake-prefix-");
        template.extend_from_slice(&MAGIC_BYTES);
        template.extend_from_slice(&0u32.to_le_bytes());
        template.extend(std::iter::repeat_n(
            0xAA,
            CAPACITY - MAGIC_LEN - LEN_PREFIX_BYTES,
        ));

        let consumer_bytes = wat::parse_str(CONSUMER_WAT).expect("wat");
        let splits = tempfile::tempdir().unwrap();
        let builtin_dir = splits.path().join("builtins");
        std::fs::create_dir_all(&builtin_dir).unwrap();
        let builtin_path = builtin_dir.join("fake-consumer.wasm");
        std::fs::write(&builtin_path, &consumer_bytes).unwrap();

        let override_dir = tempfile::tempdir().unwrap();
        std::fs::write(override_dir.path().join("config-provider.wasm"), &template).unwrap();
        let _guard = EnvGuard::set("SPLICER_BUILTINS_DIR", override_dir.path());

        // No keys inserted — this is the "no `config:` in YAML" case.
        let mut inj = Injection::from_path("metrics", builtin_path.to_str().unwrap());
        assert!(inj.builtin_config.is_empty());

        ensure_provider_for(&mut inj, splits.path()).expect("ensure");

        let path = inj
            .config_provider_path
            .as_deref()
            .expect("provider path stamped even with empty config");
        let patched = std::fs::read(path).expect("provider written");
        let parsed = parse_back(&patched);
        assert!(
            parsed.is_empty(),
            "patched provider should decode to an empty table"
        );
        // Any lookup returns None — consumers fall back to defaults.
        assert!(!parsed.contains_key("buffer"));
    }

    /// Negative case: a builtin that doesn't import the substrate
    /// must not get a config provider. `inj.config_provider_path`
    /// stays `None` and no file is written.
    #[test]
    fn ensure_provider_for_skips_non_consumer() {
        let bytes = wat::parse_str(NON_CONSUMER_WAT).expect("wat");
        let splits = tempfile::tempdir().unwrap();
        let builtin_dir = splits.path().join("builtins");
        std::fs::create_dir_all(&builtin_dir).unwrap();
        let builtin_path = builtin_dir.join("hello.wasm");
        std::fs::write(&builtin_path, &bytes).unwrap();

        // No template override needed — ensure_provider_for must
        // short-circuit before reaching builtins::load_resolved_bytes.
        let mut inj = Injection::from_path("hello", builtin_path.to_str().unwrap());
        let _guard = EnvGuard::clear("SPLICER_BUILTINS_DIR");

        ensure_provider_for(&mut inj, splits.path()).expect("ensure");
        assert!(inj.config_provider_path.is_none());
    }

    /// Restore (or remove) an env var on drop so a test doesn't leak
    /// state into others. Mirrors `with_fake_builtins`'s lock pattern,
    /// but for direct env mutation. All env-touching tests in this
    /// module share the lock through `with_fake_builtins` callers
    /// where possible; this guard is used only when the richer fake
    /// (`with_fake_builtins`) isn't expressive enough.
    struct EnvGuard {
        key: &'static str,
        prev: Option<std::ffi::OsString>,
        _lock: std::sync::MutexGuard<'static, ()>,
    }

    impl EnvGuard {
        fn lock() -> std::sync::MutexGuard<'static, ()> {
            use std::sync::Mutex;
            static LOCK: Mutex<()> = Mutex::new(());
            LOCK.lock().unwrap_or_else(|p| p.into_inner())
        }
        fn set(key: &'static str, val: &std::path::Path) -> Self {
            let lock = Self::lock();
            let prev = std::env::var_os(key);
            unsafe { std::env::set_var(key, val) };
            Self {
                key,
                prev,
                _lock: lock,
            }
        }
        fn clear(key: &'static str) -> Self {
            let lock = Self::lock();
            let prev = std::env::var_os(key);
            unsafe { std::env::remove_var(key) };
            Self {
                key,
                prev,
                _lock: lock,
            }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            unsafe {
                match self.prev.take() {
                    Some(v) => std::env::set_var(self.key, v),
                    None => std::env::remove_var(self.key),
                }
            }
        }
    }
}
